= CHANGELOG
:toc:
:sectanchors:
:sectlinks:

[#v0_15_1]
==  tokenomy-go v0.15.1 (2023-03-03)

The following asset is added to platform: avax.

The following asset has been removed from platform: mkr, snx, and trx.

The following pairs has been removed from platform: trx_btc, mkr_idk,
snx_idk, and trx_usdt.


[#v0_15_0]
==  tokenomy-go v0.15.0 (2022-11-18)

This release add the following asset:

* Solana (sol)

and remove the following asset:

* CyberMiles (cmt)
* Kybernetwork (knc)
* Monero (xmr)
* Zcash (zec)

[#v0_15_0_new_features]
===  New features

all: add bulk trading API::
+
--
The TradeBulk method can be used to cancel or create multiple orders at
the same time.
It accept the TradeBulk type with the following fields,

* pair: REQUIRED, the name of the currencies being traded, for example
  "btc_usdt".
* orders: OPTIONAL, list of orders to be placed on the market.
* cancel: OPTIONAL, list of order to be cancelled.
* timestamp: REQUIRED, the current epoch time.

The request will be processed sequentially: "orders" first, then "cancel".

Each item in the cancel and orders will return exactly one object of
BulkOrderItem in the same order as request.

* id: The unique ID for order.
  In case of failure on mass-orders or self-trade, it will return 0.
* ref_id:  The value of ref_id from the BulkOrderItem request.
* code: The status of order, 200 for success, otherwise it will be
  considered as failed.
* message: The order status or error message if returned code is not 200.
* name: The error unique identifier. This field will be set only if the
  code value is not 200.
--

[#v0_15_0_enhancements]
=== Enhancements

TKN-3112 asset: add field IsWithoutNetwork to Asset struct::


==  tokenomy-go v0.14.0 (2022.01.10)

===  New features

*  all: add method to get market summaries on WebSocket public

   The MarketSummaries method return the market summaries, its equal to
   HTTP public API /v2/market/summaries.

===  Breaking changes

*  all: rename TradeParams to ListTradeParams

   The name TradeParams indicate that the struct is for trading parameters,
   but the actual use is to fetch list of user's trades.

   In order to minimize confusion we rename the struct to ListTradeParams.

*  all: refactoring UserTrades parameter to use struct TradeParams

   Previously the UserTrades method accept seven parameters.
   If we need to add new parameter, it will changes the signature of method.

   To prevent this in the future, we changes the signature to accept
   single struct.

===  Enhancements

*  all: change default limit from 1000 to 100

   This is to make it consistent with the platform and to minimize number
   of records fetched from server.

*  all: add field Pair to MarketDepths

   The field Pair indicated which pair that the market depths data that
   client received.  This is required to distinguished broadcasted data
   on WebSocket public for market depths subscription.

*  all: add field Pair to MarketInfo

   The Pair field deprecating the Symbol field.  The idea is to make the
   field name consistent across all APIs.

*  all: add field Sort to TradeParams

   The Sort field define the order of records from UserTrades.
   Valid values is "asc" for ascending or "desc" for descending.

*  all: support ADA/IDK

*  all: realign all structs

   Size changes after alignments,

   * DepositItem changes from 56 to 40 bytes (-16 bytes)
   * Environment changes from 48 to 40 bytes (-8 bytes)
   * MarketInfo changes from 104 to 72 bytes (-32 bytes)
   * MarketTicker changes from 72 to 64 bytes (-8 bytes)
   * PublicSubscription changes from 64 to 56 (-8 bytes)
   * Trade changes from 160 to 144 bytes (-16 bytes)
   * TradeRequest changes from 80 to 72 bytes (-8 bytes)
   * User changes from 64 to 48 bytes (-16 bytes)
   * WebSocketParams changes from 288 to 248 (-40 bytes)
   * WebSocketPrivate changes from 40 to 32 (-8 bytes)
   * WebSocketPublic changes from 72 to 64 (-8 bytes)
   * WithdrawItem changes from 144 to 128 (-16 bytes)

*  all: add JSON tag omitempty for optional fields in TradeRequest

   The Method, TimeInForce, and IsPostOnly fields is optional for trade
   request, so it can be empty.

*  all: update currencies and pairs

   For currencies we add Bitcoin Cash, CyberMiles, and USDC;
   and remove Bitcoin ABC, Honest, Loopring, Lyfe, Lyfe BEP, Ontology,
   Playgame, Siacash, Six, Sushi Swap, Swipe.

   The following pair is added: bch_btc.

   The following pairs are removed: bchabc_btc, hnst_btc, lrc_btc, ont_btc,
   six_btc, swipe_btc, xlp_btc, hart_idk, hnst_idk, inx_idk, lyfebep_idk,
   pxg_idk, scc_idk, sushi_idk, swipe_idk.


*  tokenomy-go: add usdc to list of known assets
*  user_notifications: add earn related product notification type
*  all: add asset Polkadot (DOT) and pairs for dot_btc and dot_idk


==  tokenomy-go v0.13.0 (2021.05.20)

This release set the minimum Go version in go.mod to 1.16.

=== New features

* all: add parameter TimeInForce on trade request

  TimeInForce parameter only applicable if Method is "limit".
  This option may change the behaviour of order "limit" processed by broker.
  Currently, the valid values are empty "" (default) or "FOK"
  (fill-or-kill).

  If the value is empty, the order request processed normally as "limit"
  request.

  If the value is "FOK", the order will be success only if only all of
  requested amount is fulfilled, otherwise it will return as an error
  ErrTradeFillOrKill.


==  tokenomy-go v0.12.0 (2021.04.06)

=== New features

* Add parameter network to User withdraw

  The network parameter is optional, it define the network name of the asset.
  For example, for withdrawing asset TEN the network value would be "erc20".


==  tokenomy-go v0.11.1 (2021.01.17)

This release set the minimum Go version to 1.14.

=== Enhancements

*  README: replace godoc with pkg.go.dev

*  response: add method Unwrap

   The Unwrap method will return the *liberrors.E to allow
   lib/http.DefaultErrorHandler to set the HTTP response code based on
   the E's Code value.


==  tokenomy-go v0.11.0 (2020.11.24)

===  Breaking changes

*  all: rename Tick to MarketTicker
   Also, rename the MarketTicker fields to give more meaningful names,
   for example instead of Ask rename it to LowestAskPrice, so we can
   understand its meaning directly.

*  tick: remove unused IsZero method

===  New features

*  websocket_public: add method to get market prices


==  tokenomy-go v0.10.0 (2020.10.23)

This release remove deprecated API v1 package and focus only on API v2.
The API v2 package has been moved to root directory to prevent conflict with
"v2" versioning on Go modules.

===  New features

*  wspublic: add methods to subscribe and unsubscribe to topic "depths"
   The topic "depths" contains latest information about pair's depths on
   the market.

*  market_summaries: add field "Prices" and "PriceChanges"
   The field "Prices" will contains the pair last price and the field
   PriceChanges will contains the percentage between last price and
   last price before 24 hours ago.

*  depth: add field TotalBase and TotalCoin

===  Enhancements

*  response: remove the PackGob and UnpackGob methods

*  all: update list of assets and pairs

===  Chores

*  public_subscription: add field Summaries
   This field will be used to subscribe changes on market summaries.

*  market_depths: change the slice of Depth to slice of pointer to Depth


==  tokenomy-go v0.9.1 (2020.08.31)

===  Enhancements

* all: update list of available assets and pairs

Add pair Compound/IDK (comp_idk) and Tezos/IDK (xtz_idk), and remove
the asset Lyfe(erc20).

* v2/response: add methods to pack and unpack to/from gob format
* v2/client: check for error on doSecureRequest


==  tokenomy-go v0.9.0 (2020.08.13)

===  Breaking changes

* v2/client: change UserOrdersClosed parameter to time range

===  New features

* v2: add methods to manage subscription on public WebSocket

* v2: add method to cancel all open orders using REST and WebSocket


==  tokenomy-go v0.8.0 (2020.07.14)

===  Breaking changes

* all: refactoring trade method parameters

Previously the method for trade ask/bid have four parameters:
method, pair, amount, and price.

Since we want to add another parameter to trade, its not good design
to have more than three parameters in method or function, so we change
the parameters into single struct: TradeRequest.

This changes affected v1 and v2, especially v2 we need to move
WebSocketParams to root package because its required by
TradeRequest.Pack().

* v2: refactoring trade response

The field "trade" become "order" and the field "deals" become "trades".

* v2: change the API paths from `trades` into `orders`,

** `/v2/user/trades/closed` become `/v2/user/orders/closed`
** `/v2/user/trade` become `/v2/user/order`
** `/v2/user/trades/open` become `/v2/user/orders/open`

* v2: return the coin, base, and price as string with eight digit precision

===  Enhancements

* trade: remove unused field Fee


==  tokenomy-go v0.7.0 (2020.06.18)

This release add new asset name "lyfebep" and pairs "lyfebep_ikd", "idk_usdt".

===  Breaking changes

*  all: call log.Fatal if there is an error when generating signature.
   The Sign() function is essential process that must be success.
   Returning an empty string if there is an error from this function
   may result in undetected error in client side.

*  v2: rename PrivateWebSocket to WebSocketPrivate

*  all: replace TradePrice with Trade.
   Basically, TradePrice type and its contents is Trade with less fields.
   We can use the Trade type and fill only the required fields and it will
   convert to JSON with the same output.

===  New features

*  v1: use the tokenomy.Sign function to generate signature

*  v2: add parameter "offset" and "limit" to MarketTrades on REST Client

*  v2: implement client for public WebSocket.
   The public WebSocket contains three APIs that are similar with the
   REST APIs,
** MarketDepths: list of market's depths for specific pair
** MarketTicker: list of ticker information on specific pair
** MarketTrades: list of all completed trades in the market, specific to pair,
   grouped by ask and bid

*  v2: add API to withdraw user's asset

===  Enhancements

*  all: call log.Fatal if there is an error when generating signature

*  v2: add parameter "offset" and "limit" to MarketTrades on REST Client

===  Bug fixes

*  v2: fix wrong API path on MarketDepths

*  Fixes some empty responses due to variables are not passed as pointer to
   v2.Response.Data.

*  v2: check for nil on amount and price


==  tokenomy-go v0.6.0 (2020.06.05)

===  Breaking changes

*  all: rename TradeOpens to TradesOpen
*  all: move MarketTradePrices to base package

While at it, add field Pair to trade prices so client can know the
pair where trade belong to.


==  tokenomy-go v0.5.0 (2020.06.05)

===  Breaking changes

* v2: encode/decode WebSocket request/response body using base64

Due to dynamic value of WebSocket request/response body and
since the request/response will be transferred using JSON format,
it would be safe and faster if the body itself is not encoded with JSON.

For example, previously to send parameter pair as JSON object it would
result in escaped JSON syntax,

  {
      "id": 1587701148,
      "method": "GET",
      "target": "/v2/user/trades/open",
      "body": "{\"pair\":\"ten_btc\"}"
  }

The new request using base64 would be like,

  {
      "id": 1587701148,
      "method": "GET",
      "target": "/v2/user/trades/open",
      "body": "eyJwYWlyIjoidGVuX2J0YyJ9"
  }

===  Enhancements

*  v2: allow empty pair on private WebSocket UserTradesOpen

If pair is empty it will return all open trades in all pairs.


==  tokenomy-go v0.4.4 (2020.06.05)

===  Bug fixes

*  v1: set parameter asset name on trade

If trade method is sell the asset name is coin name, otherwise the asset
name is base name.

*  v2: set default trade method to "limit"


==  tokenomy-go v0.4.3 (2020.05.20)

===  Bug fixes

*  all: set TLSConfig only if IsInsecure is set

When connecting to HTTP only address, for example when testing, setting
Environment.IsInsecure to true make the connection timeout due to
connection is still using TLS.

This changes fix this issue by initializing TLSConfig only if
Environment.IsInsecure is set.


==  tokenomy-go v0.4.2 (2020.05.18)

===  Enhancements

*  UserNotifications: new type to represent user's notification preferences

The user notification preferences will be returned when calling
"/v2/user/info".


==  tokenomy-go v0.4.1 (2020.05.12)

===  Enhancements

*  environment: remove setting log flags to 0
*  v2: use the same default address for private WebSocket
*  Add constants for list of valid trade's status


==  tokenomy-go v0.4.0 (2020.05.05)

===  Breaking changes

*  trade: remove the ambiguous TradeID field

===  New features

*  v2: add methods to cancel open ask/bid using Trade object
*  v2: add method to get trade information in private WebSocket
*  v2: add method to get user information in private WebSocket

===  Enhancements

*  v2: add method to close WebSocket connection
*  v2: handle reconnect when PrivateWebSocket receive unexpected quit
*  all: define default dial and request/response timeout for HTTP client

===  Bug fixes

*  v2: fix wrong method on PrivateWebSocket cancel trade request


==  tokenomy-go v0.3.0

v2: implement private WebSocket client

The private WebSocket client can handle trade, trade cancellation,
and listing open trades.


==  tokenomy-go v0.2.1

v2: remove pair checks, let the server do the check

Due to changes on pairs on the server, client may still use the old
module that contains delisted pairs or not contains new pairs.
This may cause an unexpected errors on the client side.

To minimize this error, we remove the check on pairs and let the server
do them.


==  tokenomy-go v0.2.0

This release refactoring the struct Order and Trade in v2 to make it
consistent.
In v1, we use the term "order" and "trade" to convey the same information.
In v2, we use the term "trade" for all information related to trading,
either open or closed.

===  Breaking changes

*  Change the market trades open API from "/v2/market/orders/open" to
   "/v2/market/trades/open"

*  Change the user's trades open API from "/v2/user/orders/open" to
   "/v2/user/trades/open"

*  Change the user's trades closed API from "/v2/user/orders/closed" to
   "/v2/user/trades/closed"

*  Change the user's trade information API from "/v2/user/order" to
   "/v2/user/trade"


==  tokenomy-go v0.1.0

List of features in this release,

*  REST client for API v1, and
*  REST client for API v2


List of functionalities for each client,

*  Market,
**  Info: list of all available pairs including limit information and
    market status.
**  OrdersOpen: list the public open order book (buy and sell) for
    specific pair.
**  Summaries: retrieve the summary of all traded pairs, highest price,
    lowest price, volume, last price, token/coin name.
    This API method can also be used to discover all current traded pairs.
**  Ticker: get the price summary of an individual pair.
**  Trades: get the latest trades for a particular pair.

*  Trade,
**  Ask: put the sell order for specific asset at specific amount and
    price into the market.
**  Bid: put the buy order for specific asset at specific amount and price
    into the market.
**  CancelAsk: cancel the sell (ask) order on specific pair name and order
    ID.
**  CancelBid: cancel the buy (bid) order on specific pair name and order ID.

*  User,
**  Info: fetch the user's balance and information.
**  Order: get the detail of a specific user's open order by pair name and
    order ID.
**  OrdersClosed: list user's closed order history (buy and sell).
**  OrdersOpen list the current user's open order (buy and sell) by pair
    name.
**  Trades: list all user's history of trade.
**  Transactions: list all user's history of deposits and withdrawals from
    all assets.
**  Withdraw: withdraw user assets into another address. This method accept
    withdrawing all coins except TEN.


List of functionalities only on client API v2,

*  Market,
**  Depths: fetch list of market's depth for specific pair.
**  Prices: return list of all latest pair's prices.
